### ISSUE TITLE
[nri-docker] Document internally new cgroupsV2 metrics

### ISSUE THREAD

**Issue by marcsanmi** [newrelic/nri-docker#100]
Document all new metrics that comes with `cgroupsV2` to be able to assess when and how we should include them.

**Comment by sigilioso** [comment]
Do not miss `dbytes` and `dios` from `io.stats`, as @roobre pointed out in this (internal) [document](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2466906448/nri-docker+cgroup2+conflicting+metrics)

**Comment by marcsanmi** [comment]
https://newrelic.atlassian.net/wiki/spaces/INST/pages/2474312627/nri-docker+cgroups+breakdown+metrics
