### ISSUE TITLE
Check if metrics change by changing CPU/IO schedulers

### ISSUE THREAD

**Issue by kang-makes** [newrelic/nri-docker#123]
With the change from control groups v1 to v2 some IO metrics were lost so I wonder if there are some metrics that could be related to the schedulers configured or if the scheduler is going to add these metrics in a near future.

So we would have to test different distributions if they change the default schedulers and see if there are values that could change/be lost if we change them.  

## Priority
Nice to Have

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
