### ISSUE TITLE
cgroups v2 container metrics not collected from all containers

### ISSUE THREAD

**Issue by rowecharles** [newrelic/nri-docker#131]
## Description

When running the latest newrelic infrastructure agent (`newrelic/infrastructure:1.26.0`) as a container on a VM with cgroups v2 enabled the agent does not collect metrics about all containers on the VM.  The only container metrics that are collected are it's own container metrics and these are not correct.

## Expected Behavior

- Agent collects metrics for all containers running on the VM
- Metrics are correct for each container

## Steps to Reproduce

1. Create Container-Optimized OS VM from the [97 LTS channel](https://cloud.google.com/container-optimized-os/docs/concepts/versioning#lts_milestones).  This channel has cgroups v2 enabled
2. Create newrelic infrastructure container

    ```
    docker run --rm --name=newrelic \
      --network=host \
      --cap-add=SYS_PTRACE \
      --privileged \
      --pid=host \
      -v /:/host:ro \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /etc/newrelic/newrelic-infra.yml:/etc/newrelic-infra.yml:ro \
      newrelic/infrastructure:1.26.0
    ```

3. Create second container (doesn't matter what the container is)
4. Execute `nri-docker`

    ```
    docker exec newrelic /var/db/newrelic-infra/newrelic-integrations/bin/nri-docker
    ```

5. The output will be similar to below where there are `error fetching metrics for container` logs for each of the non newrelic containers on the VM.  There is output for the newrelic container however the metrics are not correct

    ```
    [WARN] computing Storage Driver stats: only devicemapper is supported
    [ERR] couldn't read cpu weight: open /host/sys/fs/cgroup/cpu.weight: no such file or directory
    [ERR] error fetching metrics for container 70f1950aefd7e5481c66f09d6b4fb7becfddd2ccae663e6054e93efaf34d0a71: open /host/sys/fs/docker-70f1950aefd7e5481c66f09d6b4fb7becfddd2ccae663e6054e93efaf34d0a71.scope/cgroup.controllers: no such file or directory
    {"name":"com.newrelic.docker","protocol_version":"3","integration_version":"1.7.0","data":[{"entity":{"name":"7eaceed2a81af09a5ffae883b76f46ca5483711fbe2c764bc0fb4bd01145d515","type":"docker","id_attributes":[]},"metrics":[{"commandLine":"/sbin/tini -- /usr/bin/newrelic-infra-service","containerId":"7eaceed2a81af09a5ffae883b76f46ca5483711fbe2c764bc0fb4bd01145d515",...}
    ```

## Your Environment

VM: Container Optimized OS version 97
newrelic infrastructure image: `newrelic/infrastructure:1.26.0`
nri-docker version: `1.7.0`

## Additional context

**second container metrics**

The error logs show `nri-docker` attempting to open the file `/host/sys/fs/docker-<container-id>.scope/cgroup.controllers`.  This is not the correct file with cgroup v2 metrics.  The correct file is `/host/sys/fs/cgroup/system.slice/docker-<container-id>.scope/cgroup.controllers`.

I think this is related to how the `/proc` filesystem behaves when it is mounted into a container.  The output from `/host/proc/4981/cgroup` is (pid `4981` is for second container running on the VM).

```
$ cat /host/proc/4981/cgroup
0::/../docker-70f1950aefd7e5481c66f09d6b4fb7becfddd2ccae663e6054e93efaf34d0a71.scope
```

The group starts with `/../` which when combined with the cgroups mount point (`/host/sys/fs/cgroup/`) gives the incorrect path that `nri-docker` is trying to open.

Interestingly the output of the cgroups file is different when executing on the host VM outside the container.

```
$ cat /proc/4981/cgroup
0::/system.slice/docker-70f1950aefd7e5481c66f09d6b4fb7becfddd2ccae663e6054e93efaf34d0a71.scope
```

I do not know why the file output is different when running in and outside the newrelic container.  I assume as `/proc` is a virtual filesystem there's some subtle kernel behaviour going on.

**newrelic container metrics**

The only container metrics getting collected are for the newrelic container however these are not the correct metrics.

The output from `/host/proc/1477263/cgroup` where pid `1477263` is the newrelic container is:

```
$ cat /host/proc/1477263/cgroup
0::/
```

The group is `/` which means that the metrics collect are for `/host/sys/fs/cgroup/` which are the metrics for the entire host VM not just the newrelic container.

Again the cgroup file content is different when running on the host VM outside the container

```
$ cat /proc/1477263/cgroup
0::/system.slice/docker-7eaceed2a81af09a5ffae883b76f46ca5483711fbe2c764bc0fb4bd01145d515.scope
```

**Comment by sigilioso** [comment]
Hi @rowecharles, thanks for opening the issue,

Docker [behaves slightly different](https://docs.docker.com/config/containers/runmetrics/#running-docker-on-cgroup-v2) on cgroup v2 and one of the differences is the default namespace mode (it is `host` for v1 but `private` for v2).

This explains the differences between the cgroup files obtained inside the container and in the host VM. As a result, the integration is not working as expected.

Could you add the `--cgroupns=host` argument when you run the infrastructure container and try again?
