### ISSUE TITLE
Cannot acces to docker image

### ISSUE THREAD

**Issue by RafaelAybar** [newrelic/nri-docker#15]
Hi! I have an issue trying to acces to daemon container with this command: ```docker run --rm -t -i newrelic/infrastructure:latest /bin/ash```
But i get the following error:

```/bin/ash: line 1: syntax error: unexpected "("```

Reading the docs, your docker images are based on Alpine, right? Also i have tried this command with same error: ``` docker run --rm -t -i newrelic/infrastructure:latest /bin/sh ```

**Comment by alejandrodnm** [comment]
You typed `/bin/ash` instead of `/bin/bash` in the first command.
