### ISSUE TITLE
Does not collect IP Addresses

### ISSUE THREAD

**Issue by Kav91** [newrelic/nri-docker#27]
I'm unable to move some customers away from my original nri-docker implementation as the IP addresses are not presented in this one.

Customers find this useful to check address consumption, and being able to associate the tx/rx against each address or a gateway.

Originally I had looped and flattened through each address as there can be multiple, but not sure if you'd want to separate into multiple network samples like the infra agent.

cc/ @fryckbos @jfjoly would be good to think about this given the upcoming work.

**Comment by davidgit** [comment]
This issue was closed because it has been inactive for a long time despite it can be reopened at any point if you think it still relevant.

Thank you for your contribution!
