### ISSUE TITLE
Latest nri-docker package 1.3.2 not working with latest newrelic-infra 1.12.2

### ISSUE THREAD

**Issue by rajali** [newrelic/nri-docker#36]
Hi,

Using Ansible configuration for new relic infra agent; my builds are broken since the last nri-docker release.

"nri-docker from install of nri-docker-0:1.3.2-1.x86_64 conflicts with file from package new relic-infra-0:1.12.2-el7.x86_64".

The version 1.3.1 and earlier worked fine.

**Comment by abe-ta** [comment]
I have the same issue

**Comment by abe-ta** [comment]
@gsanchezgavier 
Thanks. I see that nri-docker is included in the infra agent.
I gave up installing nri-docker at the time, and just installed the infra agent in AWS ECS.
I think the documentation at the time was wrong. The current documentation is fine.
