### ISSUE TITLE
Docker integration should know when it's running in Fargate

### ISSUE THREAD

**Issue by orion-fra** [newrelic/nri-docker#49]
## Description
When running in Fargate the ECS integration is not calling "connect" so all metadata related to the host is lost. Docker integration is also sending metrics without agent entityId. 

The result is that the metadata is not decorated and some attributes are lost:

- awsRegion
- ~ecsClusterName~
- ecsClusterArn
- ecsLaunchType

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

## [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
See initially filed tickets: https://newrelic.atlassian.net/browse/GTSE-4812
Aso solving: https://newrelic.atlassian.net/secure/RapidBoard.jspa?rapidView=1643&projectKey=GTSE&modal=detail&selectedIssue=GTSE-5145

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software and any relevant configurations. )

## Additional context
@jlegoff noticed the docker integration is using the same API used by the ECS integration and can detect if it is running inside Fargat

In case the Docker integration is running inside Fargate the integration will send those missing attributes as a metric attribute. For instance, the awsRegion is got from the ARN.

From @paologallinaharbur 
We should check that all the metadata is there from the old sample
[ODL](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJlbnRpdHktb3ZlcnZpZXctbmVyZGxldHMuZWNzLWNsdXN0ZXItb3ZlcnZpZXctZGFzaGJvYXJkIiwiZW50aXR5SWQiOiJNVFUzTnpjeU0zeEpUa1pTUVh4T1FYdzJOekUwTmpVeU16WXhOakEyTnpZNE1EazIiLCJpc092ZXJ2aWV3Ijp0cnVlLCJyZWZlcnJlcnMiOnsibGF1bmNoZXJJZCI6Im5yMS1jb3JlLmV4cGxvcmVyIiwibmVyZGxldElkIjoibnIxLWNvcmUubGlzdGluZyJ9LCJyZWZyZXNoIjoxNjAyNTk4NjI3NzAwfQ==&overlay=eyJuZXJkbGV0SWQiOiJ3YW5kYS1kYXRhLWV4cGxvcmF0aW9uLmRhdGEtZXhwbG9yZXIiLCJpbml0aWFsQWN0aXZlSW50ZXJmYWNlIjoibnJxbEVkaXRvciIsImluaXRpYWxBY2NvdW50SWQiOjIzNzAzMTEsImluaXRpYWxOcnFsVmFsdWUiOiIiLCJpbml0aWFsUXVlcmllcyI6W3siYWNjb3VudElkIjoyMzcwMzExLCJucnFsIjoiRlJPTSBDb250YWluZXJTYW1wbGUgU0VMRUNUICogd2hlcmUgZWNzQ2x1c3Rlck5hbWUgPSAncHJkX2V1LXdlc3QtMV9jYWR0X2NvcmVfc2hkJyJ9XSwiaW5pdGlhbENoYXJ0U2V0dGluZ3MiOnsiY2hhcnRUeXBlIjoiQ0hBUlRfSlNPTiIsImxpbmtlZERhc2hib2FyZElkIjpudWxsfX0=&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVFUzTnpjeU0zeEpUa1pTUVh4T1FYdzJOekUwTmpVeU16WXhOakEyTnpZNE1EazIiLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoiZW50aXR5LW92ZXJ2aWV3LW5lcmRsZXRzLmVjcy1jbHVzdGVyLW92ZXJ2aWV3LWRhc2hib2FyZCIsImlzT3ZlcnZpZXciOnRydWV9fQ==&platform[timeRange][duration]=259200000&platform[filters]=IihuYW1lIGxpa2UgJ2FsbG9jYXRpb24tbG9jYXRpb24nIG9yIGlkID0gJ2FsbG9jYXRpb24tbG9jYXRpb24nIG9yIGRvbWFpbklkID0gJ2FsbG9jYXRpb24tbG9jYXRpb24nKSI=), [NEW](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJuZXJkbGV0SWQiOiJlbnRpdHktb3ZlcnZpZXctbmVyZGxldHMuZWNzLWNsdXN0ZXItb3ZlcnZpZXctZGFzaGJvYXJkIiwiZW50aXR5SWQiOiJNVFUzTnpjeU0zeEpUa1pTUVh4T1FYdzJOekUwTmpVeU16WXhOakEyTnpZNE1EazIiLCJpc092ZXJ2aWV3Ijp0cnVlLCJyZWZlcnJlcnMiOnsibGF1bmNoZXJJZCI6Im5yMS1jb3JlLmV4cGxvcmVyIiwibmVyZGxldElkIjoibnIxLWNvcmUubGlzdGluZyJ9LCJyZWZyZXNoIjoxNjAyNTk4NzM3ODUzfQ==&overlay=eyJpbml0aWFsQWN0aXZlSW50ZXJmYWNlIjoibnJxbEVkaXRvciIsImluaXRpYWxRdWVyaWVzIjpbeyJhY2NvdW50SWQiOjE1Nzc3MjMsIm5ycWwiOiJGUk9NIENvbnRhaW5lclNhbXBsZSBTRUxFQ1QgKiBXSEVSRSBlY3NDbHVzdGVyTmFtZSA9ICdkZXYtZXUtd2VzdC0xLWFsbG9jYXRpb24tY29yZScgICJ9XSwiaW5pdGlhbENoYXJ0VHlwZSI6ImJpbGxib2FyZCIsImVkaXRNb2RlIjoiVklFVyIsInRpbWVSYW5nZSI6eyJkdXJhdGlvbiI6MjU5MjAwMDAwLCJiZWdpbl90aW1lIjpudWxsLCJlbmRfdGltZSI6bnVsbH0sIm5lcmRsZXRJZCI6IndhbmRhLWRhdGEtZXhwbG9yYXRpb24uZGF0YS1leHBsb3JlciIsImluaXRpYWxOcnFsVmFsdWUiOiIiLCJpbml0aWFsQWNjb3VudElkIjoxNTc3NzIzLCJpbml0aWFsQ2hhcnRTZXR0aW5ncyI6eyJjaGFydFR5cGUiOiJDSEFSVF9KU09OIiwibGlua2VkRGFzaGJvYXJkSWQiOm51bGx9LCJpbml0aWFsVGltZVdpbmRvd092ZXJyaWRlIjpudWxsfQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiwiZW50aXR5SWQiOiJNVFUzTnpjeU0zeEpUa1pTUVh4T1FYdzJOekUwTmpVeU16WXhOakEyTnpZNE1EazIiLCJzZWxlY3RlZE5lcmRsZXQiOnsibmVyZGxldElkIjoiZW50aXR5LW92ZXJ2aWV3LW5lcmRsZXRzLmVjcy1jbHVzdGVyLW92ZXJ2aWV3LWRhc2hib2FyZCIsImlzT3ZlcnZpZXciOnRydWV9fQ==&platform[timeRange][duration]=259200000&platform[filters]=IihuYW1lIGxpa2UgJ2FsbG9jYXRpb24tbG9jYXRpb24nIG9yIGlkID0gJ2FsbG9jYXRpb24tbG9jYXRpb24nIG9yIGRvbWFpbklkID0gJ2FsbG9jYXRpb24tbG9jYXRpb24nKSI=)

https://github.com/newrelic/nri-ecs/blob/e2b3668bb8b244eda85ce113abac3d2e41251834/internal/metadata/v3/v3.go#L165

https://github.com/newrelic/nri-docker/blob/master/src/docker.go#L47

impersonate - See comments in [CoreINT-337](https://newrelic.atlassian.net/browse/COREINT-337)

**Comment by roobre** [comment]
Following internal discussion, it was revealed that this issue (host metadata missing in `ContainerSample` and other events)  was caused by having the agent run with `is_forward_only` set. In this mode, the agent does not send any host information and therefore the backend cannot decorate said events.

This configuration (`is_forward_only` set) is considered legacy, and the recommended approach is to replace it with `is_secure_forward_only` as recommended in the [Fargate/ECS integration](https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/installation/install-ecs-integration). Using this configuration, the attributes mentioned above appear correctly.
