### ISSUE TITLE
Support EKS Fargate

### ISSUE THREAD

**Issue by AlexeyRaga** [newrelic/nri-docker#67]
## Is your feature request related to a problem? Please describe.
Looks like there is currently no way to use NewRelic to monitor EKS FarGate nodes.

## Feature Description
NewRelic supports AWS EKS nicely, but only supports ECS version of Fargate. It is currently the only thing that holds us back from using EKS Fargate, and it would be nice if NewRelic finally supported EKS Fargate.

## Describe Alternatives
DataDog provides an agent that can be used as a sidecar in EKS Fargate-enabled pods. That could be our alternative if NewRelic won't be able to support EKS Fargate.

## Priority
[Must Have, Blocker]

**Comment by mangulonr** [comment]
Hi Alexey

Thank you for your feedback.

We're going to launch an open beta EKS Fargate integration in 1-2 weeks.
I will notify you once is launched.

We will really love your feedback which will help us to improve even more our EKS new integration.

Regards

**Comment by AlexeyRaga** [comment]
Thanks, can't wait for it to happen!

**Comment by mangulonr** [comment]
Hi @AlexeyRaga 

We just released our beta EKS Fargate integration.

Please, take a look to our [documentation](https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/install-fargate-integration/) to find more information.
