### ISSUE TITLE
[nri-docker] Update Documentation with Cgroupsv2

### ISSUE THREAD

**Issue by alvarocabanas** [newrelic/nri-docker#85]
- Update Documentation explaining the new cgroups possible changes (not clear if all metrics will be present since some Cgroups controllers don’t exist anymore) 
- Also update docker versions supported
- Improve docs in general for docker [docker-docs](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-instrumentation-infrastructure-monitoring/)

**Comment by gsanchezgavier** [comment]
@marcsanmi  do not forget to update the docs with the removed metrics on cgroups v2

**Comment by marcsanmi** [comment]
> @marcsanmi do not forget to update the docs with the removed metrics on cgroups v2

@sigilioso is working  on that task while adapting the MetricsFetcher for cgroupsV2 and seems we'll be able to report all of them.

**Comment by marcsanmi** [comment]
Update NR docs in the [Requirements](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-instrumentation-infrastructure-monitoring/#requirements) section when we are about to release with a callout reflecting something like:

``` Support for operative systems using Control Group v2 is included from Infrastructure agent v.1.x.x and nri docker v1.7.0```

**Comment by sigilioso** [comment]
Besides updating the doc requirements to say we support cgroup2 it would be nice to review the documentation for the metrics bellow:

- `cpuLimitCores` (quotas and time unit)
-  `cpuShares` ([refers to cpu weights](https://kernel.googlesource.com/pub/scm/linux/kernel/git/glommer/memcg/+/cpu_stat/Documentation/cgroups/cpu.txt) and weight scale (and default value) may be different in [cgroup2](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#cpu-interface-files)

**Comment by marcsanmi** [comment]
NR docs PR https://github.com/newrelic/docs-website/pull/7628
